### ISSUE TITLE
Storms rarely spawning

### ISSUE THREAD

**Issue by KlutchGTR** [Mrbt0907/Weather2-Remastered#105]
I am sorry if I don't know since I am just new to Weather2 Remastered (I am used to the original Weather2), How to make storms spawn often? Forgot to add, whenever there is a hailing supercell, it just weakens instead of tornado.

**Comment by Mrbt0907** [comment]
So by default, tornados spawn about every 2-10 minecraft days in the world. And the probability for any storm to turn into a tornado/hurricane have been reduced.

To tune how often storms spawn, go to the EZ Gui -> Storms Tab -> Then change Frequency Of Storms to whatever you want. It goes from extremely rare to almost every minecraft hour.

As for the probability for storms to become tornados/hurricanes, head to the Advanced Settings -> Change to the weather2Storm page and raise the chances for tornado's and hurricanes higher. Make sure to lower chance_for_supercell and chance_for_hailing_supercell as they are responsible for storms always stopping at supercell stage.

The next update will change how that works since it really doesn't make sense.

**Comment by KlutchGTR** [comment]
Ahh thank you!

**Comment by Mrbt0907** [comment]
No problem. Enjoy the update man.
