### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by happysmash27** [Mrbt0907/Weather2-Remastered#133]
Hello! I would like to contribute to this mod for the purposes of integrating with SereneSeasons, but there is no license set in the source code. Would it be possible to license it under LGPL like the 1.18 version of the original mod (https://github.com/Corosauce/weather2/blob/1.18/LICENSE.txt)? Also pinging @Corosauce in case permission is needed from original author too. 

Looking to add this on 1.12.2 instead of newer versions because my modpack is on 1.12.2 and more importantly, SereneSeasons is only open source on the older versions.

**Comment by happysmash27** [comment]
On second thought, upon looking through the source code I *think* the temperature detection that whether to snow or not is based on is actually from CoroUtilCompatibility, not the Weather2 mod itself, so I will look to that mod to implement this compatibility. 

Still, in general a license would still be very helpful for contributions from others, so I still think it would be a good idea to add one.

**Comment by happysmash27** [comment]
Hmm. According to the source code it looks like it *is* compatible with Serene Seasons, actually, and Tough as Nails too! Yet, it isn't actually detecting them according to the logs. Guess that is more of an issue for CoreUtil though.

**Comment by happysmash27** [comment]
Third update, upon searching through the source code it looks like CoroUtil is *already integrated* with SereneSeasons. Not sure if winter has not actually started yet or if it is not going through properly, for some reason. Or, maybe this mod is compatible with SereneSeasons, and the original I am actually using is not (I only searched the source code of this one). I'm going to upgrade to this version.

**Comment by Mrbt0907** [comment]
Coroutil has limited compatibilities built into it. The issue with the 2.8 branch is the internal code was almost completely rewritten to allow fronts, which broke some compatibilities. I will soon make a full update to the compatibility to work much better than it currently does now.

As for the license, the 1.12.2 branch does not have a license, which is why I myself did not incorporate a license. However, once I am able to negotiate with Corosus about what I can do with my future plans, I should be able to obtain a license that coros wants me to integrate.

Not sure when this will happen, so I will keep everyone posted about this.

**Comment by CosmicHikari** [comment]
I will look into this and try to get an all clear for this. Thanks for your dedication!

**Comment by CosmicHikari** [comment]
Any negotiation with Corosus must wait for a bit, as he's currently busy with work ^^

**Comment by CosmicHikari** [comment]
After a chat with Coro, it has been decided we will follow his licensing of All Rights Reserved.
