### ISSUE TITLE
storms C0, C1, C2, C3, C4, C5, EF0, EF1, EF2, EF3, EF4, EF5 almost never, if ever, appear

### ISSUE THREAD

**Issue by YoshihiroFR** [Mrbt0907/Weather2-Remastered#77]
**storms C0, C1, C2, C3, C4, C5, EF0, EF1, EF2, EF3, EF4, EF5 almost never, if ever, appear**
I can stay to play the game for as long as possible but these storms never appear naturally, I tried parameters but it does not work for all that.

**Comment by Mrbt0907** [comment]
Try deleting all weather2 configs and modifying spawn rates within the EZ GUI and see if that fixes your issue

**Comment by Acwire** [comment]
tried this  and the issue is still here. tornados almost never spawn. They develop fully into hail storms then degrade.  I even changed the tick multipliers and chance of storms and chance of EF0-5 all to high and they still don't spawn. any other fixes?

**Comment by Acwire** [comment]
I also tried chagning alot of other things in the advanced tab in the EZ GUI and it still does nothing. Even tried changing the EZ GUI storm chance setting which only increases the quantity of storms but they still all develop into hail storms then degrade and don't spawn any tornado or cyclone

**Comment by Mrbt0907** [comment]
I'll take a look into this to see how I did the chance values and I will tell you how to fix this.

**Comment by Mrbt0907** [comment]
Figured out the issue. The storm chances start with **chance_for_supercell** up to **chance_for_ef5/chance_for_c5**. If chance for supercell is 100% all storms will be supercells. If chance for ef0s is 100% and others below are 0, then it will always spawn an ef0.

To fix this, lower the chances for a storm to develop into a supercell/hailing supercell so they have a higher chance to become a tornado/supercell.

I'll fix this logic in the next update to start in decending order (Ef5 > Supercell instead of Supercell > EF5)

**Comment by Acwire** [comment]
ah I see yes this worked. It would make more sense to decent the order as that's how I believed it worked. also another small issue is the shader compatibility does not work at all? its not a big deal just why is it there if it doesn't really serve a purpose

**Comment by Mrbt0907** [comment]
Some compatibility modes don't work well, hence why it is suffixed with (-). The issue is I don't know how to change how rendering is done with the particles, so I just adjust a couple variables that work best for the shaders listed in the shader compatibility modes.

Shaders that are not suffixed with (-) should work with your system.

Note: AMD Graphics cards are not supported well with this mod.
